---
all:
  children:
    proxmox_cluster:
      children:
        proxmox_hosts:
          hosts:
            pve1:
              ansible_host: "{{ lookup('env', 'PROXMOX_HOST') | default('localhost', true) }}"
              ansible_port: "{{ lookup('env', 'PROXMOX_SSH_PORT') | default('22', true) }}"
              ansible_user: "{{ lookup('env', 'PROXMOX_SSH_USER') | default('root', true) }}"
              node_name: "{{ lookup('env', 'PROXMOX_NODE_NAME') | default('pve', true) }}"
          vars:
            ansible_python_interpreter: /usr/bin/python3
            proxmox_api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
            proxmox_api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
            proxmox_api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
            proxmox_api_token_secret: "{{ lookup('env', 'PROXMOX_SECRET') }}"
            proxmox_api_verify_ssl: "{{ lookup('env', 'PROXMOX_VERIFY_SSL') | default('false', true) }}"
    
    # Group for VMs managed by Proxmox
    managed_vms:
      children:
        app_servers:
          hosts:
            app1:
              ansible_host: 192.168.1.101
            app2:
              ansible_host: 192.168.1.102
        db_servers:
          hosts:
            db1:
              ansible_host: 192.168.1.201
    
    # Group for containers managed by Proxmox
    managed_containers:
      children:
        web_servers:
          hosts:
            web1:
              ansible_host: 192.168.1.151
            web2:
              ansible_host: 192.168.1.152
